FROM llvm-mingw-my2-base:latest

WORKDIR /build
COPY wrappers/*.sh wrappers/*.c wrappers/*.h ./wrappers/
COPY ./my_build-mingw-w64.sh  ./my_build-all.sh  ./my_build-llvm.sh ./my_build-lldb-mi.sh ./strip-llvm.sh ./install-wrappers.sh ./build-mingw-w64-tools.sh ./build-mingw-w64.sh \
    ./my_build-compiler-rt.sh ./my_build-libcxx.sh ./my_build-mingw-w64-libraries.sh ./my_build-openmp.sh ./my_build_mimalloc.sh ./


ENV TOOLCHAIN_PREFIX=/opt/llvm-mingw
ENV PATH=$TOOLCHAIN_PREFIX/bin:$ORG_PATH

RUN ./my_build-all.sh /build/Win32 --host=i686-w64-mingw32                                   
RUN ./my_build-llvm.sh /build/Win32Static --disable-dylib --host=i686-w64-mingw32

RUN cp -rf /build/Win32/i686-w64-mingw32/bin/* /build/Win32/bin/

ENV TOOLCHAIN_PREFIX=/opt/llvm-linux
ENV PATH=$TOOLCHAIN_PREFIX/bin:$ORG_PATH

RUN ./my_build-all.sh /build/Lin32 --host=i686-linux-gnu --disable-cfguard --build-linux --host-clang=/opt/llvm-linux/bin/i686-linux-gnu-clang
RUN ./my_build-llvm.sh /build/Lin32Static --use-exsting-compiler --disable-dylib --host=i686-linux-gnu

RUN cp -rf /build/Lin32/i686-linux-gnu/bin/* /build/Lin32/bin/


                                                                