FROM llvm-mingw-my-base:latest

RUN ./my_build-all.sh build/Windows32 --host=x86_64-w64-mingw32 
RUN ./my_build-all.sh build/Linux32 

RUN ./my_build-llvm_pgo_pre.sh build/win_pgo_pre32 --host=x86_64-w64-mingw32 --lto

# ./my_build-llvm_pgo_post.sh build/Windows32 --host=x86_64-w64-mingw32 --lto
# ./my_build-llvm_pgo_post.sh build/Linux32  --lto


