FROM llvm-mingw:latest

RUN dpkg --add-architecture i386 && apt-get update -qq && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -qqy --no-install-recommends \
    tmux  && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build

ENV TOOLCHAIN_PREFIX=/opt/llvm-linux

ARG TOOLCHAIN_ARCHS="i686 x86_64" # armv7 aarch64"

ARG DEFAULT_CRT=

ARG CFGUARD_ARGS=
ENV HOST_ARG=--host=x86_64-linux-gnu

COPY wrappers/*.sh wrappers/*.c wrappers/*.h ./wrappers/

ARG TOOLCHAIN_ARCHS="riscv32"
ENV HOST_ARG=--host=riscv32-unknown-elf
COPY my_build-compiler-rt.sh ./
RUN ./my_build-compiler-rt.sh $TOOLCHAIN_PREFIX --use-exsting-compiler --disable-cfguard $HOST_ARG

ARG TOOLCHAIN_ARCHS="i686 x86_64" # armv7 aarch64"
ENV HOST_ARG=--host=x86_64-linux-gnu
#RUN ./build-mingw-w64.sh $TOOLCHAIN_PREFIX --with-default-msvcrt=$DEFAULT_CRT 
#RUN ./build-mingw-w64-tools.sh $TOOLCHAIN_PREFIX
RUN ./my_build-compiler-rt.sh $TOOLCHAIN_PREFIX --use-exsting-compiler --disable-cfguard $HOST_ARG
RUN cp -rf  /opt/llvm-linux/lib/clang/18/lib/linux /opt/llvm-mingw/lib/clang/18/lib/
COPY my_build-libcxx.sh  ./
RUN ./my_build-libcxx.sh $TOOLCHAIN_PREFIX --use-exsting-compiler --disable-cfguard $HOST_ARG
#RUN ./build-mingw-w64-libraries.sh $TOOLCHAIN_PREFIX 


ARG TOOLCHAIN_ARCHS="x86_64 i686 riscv32 armv7" 
COPY my_build-llvm.sh ./
RUN ./my_build-llvm.sh $TOOLCHAIN_PREFIX --use-exsting-compiler $HOST_ARG
COPY my_build-lldb-mi.sh install-wrappers.sh ./strip-llvm.sh ./
RUN ./my_build-lldb-mi.sh $TOOLCHAIN_PREFIX --use-exsting-compiler $HOST_ARG
RUN ./strip-llvm.sh $TOOLCHAIN_PREFIX $HOST_ARG
RUN ./install-wrappers.sh $TOOLCHAIN_PREFIX 

ARG TOOLCHAIN_ARCHS="i686 x86_64" # armv7 aarch64"
RUN cp /opt/llvm-linux/x86_64-linux-gnu/lib/* /opt/llvm-linux/lib
RUN ./my_build-compiler-rt.sh $TOOLCHAIN_PREFIX --disable-cfguard $HOST_ARG --build-sanitizers 
#RUN ./build-openmp.sh $TOOLCHAIN_PREFIX 