FROM llvm-mingw:latest

RUN apt-get clean -y && rm -rf /var/lib/apt/lists/* 
RUN dpkg --add-architecture i386 && apt-get update -qqy
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -qqy --no-install-recommends \
    tmux gcc-multilib g++-multilib  libstdc++-11-dev:i386 build-essential python3-pip && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build

RUN pip install pyyaml

# Download and extract GCC source code
COPY my_build_gcc_etc.sh ./
RUN ./my_build_gcc_etc.sh
