FROM llvm-mingw:latest

RUN dpkg --add-architecture i386 && apt-get update -qqy
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -qqy --no-install-recommends \
    vim tmux gcc-multilib g++-multilib libstdc++-11-dev:i386 libgmp-dev libgmp-dev:i386 libmpfr-dev:i386 libmpc-dev:i386 libmpfr-dev libmpc-dev build-essential python3-pip manpages-dev libisl-dev flex bison && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

