RUN ./my_build-lldb-mi.sh $TOOLCHAIN_PREFIX --use-exsting-compiler $HOST_ARG
RUN ./strip-llvm.sh $TOOLCHAIN_PREFIX $HOST_ARG
RUN ./install-wrappers.sh $TOOLCHAIN_PREFIX 

ARG TOOLCHAIN_ARCHS="i686 x86_64" # armv7 aarch64"
RUN cp /opt/llvm-linux/x86_64-linux-gnu/lib/* /opt/llvm-linux/lib
RUN ./my_build-compiler-rt.sh $TOOLCHAIN_PREFIX --disable-cfguard $HOST_ARG --build-sanitizers 
#RUN ./build-openmp.sh $TOOLCHAIN_PREFIX 



echo "./my_build-compiler-rt.sh ${PREFIX} ${HOST_ARGS} --build-sanitizers"
./my_build-compiler-rt.sh $PREFIX $HOST_ARGS --build-sanitizers # CFGUARD_ARGS intentionally omitted
if [ -z "$BUILD_LINUX" ]; then
echo "./build-openmp.sh ${PREFIX} ${CFGUARD_ARGS} "
./build-openmp.sh $PREFIX $CFGUARD_ARGS
fi
echo "my_build_mimalloc ${PREFIX} --use-exsting-compiler ${CFGUARD_ARGS}"
./my_build_mimalloc.sh $PREFIX  --use-exsting-compiler $CFGUARD_ARGS